### ISSUE TITLE
pnasnet models  issue

### ISSUE THREAD

**Issue by wangbixing** [mindspore-ecosystem/mindcv#184]
![image](https://user-images.githubusercontent.com/31263632/196370980-213534b7-852a-43a4-88d3-6e61e1b7cc5f.png)

**Comment by geniuspatrick** [comment]
Introduced by changing default value of `num_classes` in `config.py`  (pr: #172)(commit: 307f4c0722e9d912dc1cb880237e4ce4430d1ec6).
@SamitHuang Please resolve this.
